"""add blacklist

Revision ID: 434bd6f80699
Revises: 22ce96588fe5
Create Date: 2020-03-10 14:18:38.310278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434bd6f80699'
down_revision = '22ce96588fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###
