"""add diaries

Revision ID: 6605b44b9134
Revises: 2a423d9e80a9
Create Date: 2020-02-17 02:12:42.628714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6605b44b9134'
down_revision = '2a423d9e80a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diaries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diaries_timestamp'))

    op.drop_table('diaries')
    # ### end Alembic commands ###
